/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Artists */
        get: operations["search_artists_api_artists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/{export_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_api_exports__export_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel Job */
        delete: operations["cancel_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard Job */
        post: operations["discard_job_api_jobs__job_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Busca no YouTube (texto) ou lê um link. `items` vazio = nenhum resultado;
         *     YouTube indisponível responde 502 `youtube_unavailable`.
         */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /** Update Session */
        patch: operations["update_session_api_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/sessions/{session_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exports */
        get: operations["list_exports_api_sessions__session_id__exports_get"];
        put?: never;
        /**
         * Create Export
         * @description Exporta o mix (WAV ou MP3 320). Sem `stems` no corpo, usa o mix salvo da sessão.
         */
        post: operations["create_export_api_sessions__session_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/mix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mix */
        get: operations["get_mix_api_sessions__session_id__mix_get"];
        /** Save Mix */
        put: operations["save_mix_api_sessions__session_id__mix_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/peaks/{stem}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stem Peaks
         * @description `{"duration_s": float, "peaks": [0–1, ...]}` (pico absoluto por ponto, ~1600 pontos).
         */
        get: operations["stem_peaks_api_sessions__session_id__peaks__stem__json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Session
         * @description Confirma o rascunho e o põe na fila de processamento.
         */
        post: operations["process_session_api_sessions__session_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reprocess Session
         * @description Processa de novo uma sessão pronta ou que falhou (409 se já houver job ativo).
         */
        post: operations["reprocess_session_api_sessions__session_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/stems/{stem}.mp3": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stem Audio */
        get: operations["stem_audio_api_sessions__session_id__stems__stem__mp3_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Update */
        get: operations["get_update_api_system_update_get"];
        put?: never;
        /** Start Update */
        post: operations["start_update_api_system_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtistOut */
        ArtistOut: {
            /** Name */
            name: string;
            /** Sessions */
            sessions: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorOut */
        ErrorOut: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * ExportCreate
         * @description Pedido de export. Sem `stems`, vale o mix salvo da sessão.
         */
        ExportCreate: {
            format: components["schemas"]["ExportFormat"];
            preset?: components["schemas"]["MixPreset"] | null;
            /** Stems */
            stems?: {
                [key: string]: components["schemas"]["StemMix"];
            } | null;
        };
        /**
         * ExportFormat
         * @enum {string}
         */
        ExportFormat: "wav" | "mp3";
        /** ExportListOut */
        ExportListOut: {
            /** Items */
            items: components["schemas"]["ExportOut"][];
        };
        /** ExportOut */
        ExportOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** File Name */
            file_name: string;
            /** Finished At */
            finished_at: string | null;
            format: components["schemas"]["ExportFormat"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lufs */
            lufs: number | null;
            preset: components["schemas"]["MixPreset"] | null;
            /** Progress */
            progress: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Size Bytes */
            size_bytes: number | null;
            state: components["schemas"]["ExportState"];
            /** Stems */
            stems: {
                [key: string]: components["schemas"]["StemMix"];
            };
        };
        /**
         * ExportState
         * @enum {string}
         */
        ExportState: "queued" | "running" | "done" | "failed";
        /** ExportUpdatedData */
        ExportUpdatedData: {
            export: components["schemas"]["ExportOut"];
        };
        /** ExportUpdatedEvent */
        ExportUpdatedEvent: {
            data: components["schemas"]["ExportUpdatedData"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "export.updated";
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Db
             * @enum {string}
             */
            db: "ok" | "outdated" | "error";
            /**
             * Ffmpeg
             * @enum {string}
             */
            ffmpeg: "ok" | "missing";
            /**
             * Gpu
             * @enum {string}
             */
            gpu: "ok" | "unavailable" | "unknown";
            /**
             * Js Runtime
             * @enum {string}
             */
            js_runtime: "ok" | "missing";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Ytdlp */
            ytdlp: string;
        };
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "process" | "export";
        /** JobListOut */
        JobListOut: {
            /** Items */
            items: components["schemas"]["JobOut"][];
        };
        /** JobOut */
        JobOut: {
            /** Attempt */
            attempt: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dismissed At */
            dismissed_at: string | null;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Eta S */
            eta_s: number | null;
            /** Export Id */
            export_id: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["JobKind"];
            /** Position */
            position: number | null;
            /** Progress */
            progress: number;
            session: components["schemas"]["SessionOut"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            stage: components["schemas"]["SessionState"] | null;
            /** Started At */
            started_at: string | null;
            state: components["schemas"]["JobState"];
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "queued" | "running" | "done" | "failed" | "cancelled";
        /** JobUpdatedData */
        JobUpdatedData: {
            job: components["schemas"]["JobOut"];
        };
        /** JobUpdatedEvent */
        JobUpdatedEvent: {
            data: components["schemas"]["JobUpdatedData"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "job.updated";
        };
        LiveEvent: components["schemas"]["SessionUpdatedEvent"] | components["schemas"]["SessionDeletedEvent"] | components["schemas"]["JobUpdatedEvent"] | components["schemas"]["ExportUpdatedEvent"];
        /**
         * MixPreset
         * @enum {string}
         */
        MixPreset: "original" | "no_vocals" | "no_drums" | "no_bass" | "vocals_only" | "custom";
        /** MixStateIn */
        MixStateIn: {
            /** Loop A S */
            loop_a_s?: number | null;
            /** Loop B S */
            loop_b_s?: number | null;
            preset: components["schemas"]["MixPreset"];
            /** Stems */
            stems: {
                [key: string]: components["schemas"]["StemMix"];
            };
        };
        /** MixStateOut */
        MixStateOut: {
            /** Loop A S */
            loop_a_s?: number | null;
            /** Loop B S */
            loop_b_s?: number | null;
            preset: components["schemas"]["MixPreset"];
            /** Stems */
            stems: {
                [key: string]: components["schemas"]["StemMix"];
            };
            /** Updated At */
            updated_at: string | null;
        };
        /** ReleaseNotes */
        ReleaseNotes: {
            /** Sections */
            sections: components["schemas"]["ReleaseNotesSection"][];
            /** Version */
            version: string;
        };
        /** ReleaseNotesSection */
        ReleaseNotesSection: {
            /** Items */
            items: string[];
            /** Title */
            title: string;
        };
        /** SearchOut */
        SearchOut: {
            /** Items */
            items: components["schemas"]["SearchResultOut"][];
        };
        /**
         * SearchResultOut
         * @description Um resultado da busca. Os campos casam com o `SessionCreate` (rascunho).
         */
        SearchResultOut: {
            /** Artist */
            artist: string;
            /** Duration S */
            duration_s: number | null;
            /** Source Channel */
            source_channel: string | null;
            /** Source Title */
            source_title: string;
            /** Source Url */
            source_url: string;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Title */
            title: string;
        };
        /**
         * SessionCreate
         * @description Rascunho de sessão: fonte escolhida em Descobrir + identidade confirmada.
         */
        SessionCreate: {
            /** Artist */
            artist: string;
            /** Duration S */
            duration_s?: number | null;
            /** Source Channel */
            source_channel?: string | null;
            /** Source Title */
            source_title?: string | null;
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Title */
            title: string;
        };
        /** SessionDeletedData */
        SessionDeletedData: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** SessionDeletedEvent */
        SessionDeletedEvent: {
            data: components["schemas"]["SessionDeletedData"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "session.deleted";
        };
        /** SessionListOut */
        SessionListOut: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Items */
            items: components["schemas"]["SessionOut"][];
            /** Total */
            total: number;
        };
        /**
         * SessionMetrics
         * @description Loudness do áudio original (medido com `loudnorm`); nulo se não deu para medir.
         */
        SessionMetrics: {
            /** Lufs */
            lufs: number | null;
            /** True Peak Db */
            true_peak_db: number | null;
        };
        /** SessionOut */
        SessionOut: {
            /** Artist */
            artist: string;
            /** Code */
            code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration S */
            duration_s: number | null;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            metrics: components["schemas"]["SessionMetrics"] | null;
            /** Processed At */
            processed_at: string | null;
            /** Progress */
            progress: number;
            /** Source Channel */
            source_channel: string | null;
            /** Source Title */
            source_title: string | null;
            /** Source Url */
            source_url: string;
            state: components["schemas"]["SessionState"];
            /** Stems */
            stems: components["schemas"]["Stem"][];
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SessionPatch */
        SessionPatch: {
            /** Artist */
            artist?: string | null;
            /** Title */
            title?: string | null;
        };
        /**
         * SessionSort
         * @enum {string}
         */
        SessionSort: "newest" | "oldest" | "title" | "artist" | "longest" | "shortest";
        /**
         * SessionState
         * @enum {string}
         */
        SessionState: "draft" | "queued" | "downloading" | "separating" | "ready" | "failed";
        /** SessionUpdatedData */
        SessionUpdatedData: {
            session: components["schemas"]["SessionOut"];
        };
        /** SessionUpdatedEvent */
        SessionUpdatedEvent: {
            data: components["schemas"]["SessionUpdatedData"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "session.updated";
        };
        /**
         * Stem
         * @enum {string}
         */
        Stem: "vocals" | "drums" | "bass" | "other";
        /** StemMix */
        StemMix: {
            /**
             * Mute
             * @default false
             */
            mute: boolean;
            /**
             * Pan
             * @default 0
             */
            pan: number;
            /**
             * Solo
             * @default false
             */
            solo: boolean;
            /**
             * Volume
             * @default 100
             */
            volume: number;
        };
        /** SystemUpdateOut */
        SystemUpdateOut: {
            /** Active Jobs */
            active_jobs: number;
            /** Available */
            available: boolean;
            /** Can Update */
            can_update: boolean;
            /**
             * Check
             * @enum {string}
             */
            check: "ok" | "unavailable";
            /** Checked At */
            checked_at: string | null;
            /** Current Version */
            current_version: string;
            last_run: components["schemas"]["UpdateRunOut"] | null;
            /** Latest Version */
            latest_version: string | null;
            /** Notes */
            notes: components["schemas"]["ReleaseNotes"][];
        };
        /**
         * UpdateRunOut
         * @description Uma atualização pedida pelo app.
         */
        UpdateRunOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** From Version */
            from_version: string;
            /** Id */
            id: number;
            /** Message */
            message: string | null;
            state: components["schemas"]["UpdateState"];
            /** Target Version */
            target_version: string;
        };
        /**
         * UpdateState
         * @description Atualização do Stemma disparada pelo app (ADR 0015).
         * @enum {string}
         */
        UpdateState: "running" | "succeeded" | "failed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_artists_api_artists_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistOut"][];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    download_export_api_exports__export_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": unknown;
                    "audio/wav": unknown;
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    discard_job_api_jobs__job_id__discard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                q?: string | null;
                state?: components["schemas"]["SessionState"][] | null;
                sort?: components["schemas"]["SessionSort"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    update_session_api_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_exports_api_sessions__session_id__exports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportListOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    create_export_api_sessions__session_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_mix_api_sessions__session_id__mix_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MixStateOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    save_mix_api_sessions__session_id__mix_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MixStateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MixStateOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    stem_peaks_api_sessions__session_id__peaks__stem__json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                stem: components["schemas"]["Stem"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    process_session_api_sessions__session_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    reprocess_session_api_sessions__session_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    stem_audio_api_sessions__session_id__stems__stem__mp3_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                stem: components["schemas"]["Stem"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": unknown;
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_update_api_system_update_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemUpdateOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    start_update_api_system_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRunOut"];
                };
            };
            /** @description Não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflito com o estado atual */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Entrada inválida */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
