/** Textos da interface em PT-BR. Único lugar com texto de UI. */

const plural = (n: number, one: string, many: string) => `${String(n)} ${n === 1 ? one : many}`;
export const ordinal = (n: number) => `${String(n)}º`;

export const strings = {
  app: {
    name: 'stemma',
    loading: 'Carregando…',
  },
  nav: {
    label: 'Navegação principal',
    discover: 'Descobrir',
    library: 'Biblioteca',
    mixer: 'Mixer',
  },
  common: {
    cancel: 'Cancelar',
    close: 'Fechar',
    retry: 'Tentar de novo',
    save: 'Salvar',
    more: 'Mais ações',
    reload: 'Recarregar',
    loadMore: 'Carregar mais',
  },
  states: {
    draft: 'Rascunho',
    queued: 'Na fila',
    downloading: 'Baixando',
    separating: 'Separando',
    ready: 'Pronta',
    failed: 'Falhou',
  },
  chip: {
    queuedAt: (position: number) => `Na fila · ${ordinal(position)}`,
    progress: (label: string, pct: number) => `${label} ${String(Math.round(pct))}%`,
  },
  errors: {
    title: 'Algo deu errado',
    unexpected: 'A tela encontrou um erro inesperado. Recarregue para continuar.',
    loadFailed: 'Não deu para carregar.',
    notFoundTitle: 'Página não encontrada',
    notFoundBody: 'O endereço não existe ou a sessão foi excluída.',
    backHome: 'Ir para Descobrir',
  },
  discover: {
    title: 'O que vamos separar hoje?',
    searchLabel: 'Buscar música',
    searchPlaceholder: 'Nome da música ou link do YouTube',
    paste: 'Colar link',
    pasteHint: 'colar link',
    clear: 'Limpar busca',
    recentTitle: 'Continuar de onde parou',
    results: (n: number) => plural(n, 'resultado', 'resultados'),
    resultsTapHint: 'toque para escolher',
    resultsLabel: 'Resultados da busca',
    emptyTitle: (q: string) => `Nada para “${q}”`,
    emptyBody: 'Confira a grafia ou cole o link do vídeo direto.',
    unavailableTitle: 'YouTube indisponível',
    unavailableBody: 'A busca não respondeu. Tente de novo em alguns segundos.',
    linkErrorTitle: 'Não deu para abrir o link',
  },
  identity: {
    step: 'Passo 2 de 2',
    title: 'Confirme artista e título',
    artist: 'Artista',
    songTitle: 'Título',
    usedBefore: (n: number) => `já usado · ${plural(n, 'sessão', 'sessões')}`,
    sessions: (n: number) => plural(n, 'sessão', 'sessões'),
    prefilled: 'Pré-preenchido a partir do YouTube.',
    startsNow: 'Fila livre · começa agora',
    ahead: (n: number, eta: string | null) =>
      `${plural(n, 'job', 'jobs')} na frente${eta ? ` · começa em ${eta}` : ''}`,
    separate: 'Separar',
    required: 'Preencha artista e título.',
    queued: (code: string) => `${code} entrou na fila`,
    follow: 'Acompanhar',
    keptAsDraft: (code: string) => `${code} ficou como rascunho`,
    continue: 'Continuar',
  },
  processing: {
    title: 'Processamento',
    gpu: 'GPU · 1 por vez',
    open: 'Abrir processamento',
    expand: 'Expandir processamento',
    collapse: 'Recolher processamento',
    now: 'Agora',
    downloaded: 'Baixado',
    downloading: 'Baixando',
    separating: 'Separando',
    ready: 'Pronto',
    remaining: (eta: string) => `${eta} restantes`,
    inQueue: 'na fila',
    queuedStarts: (eta: string | null) => (eta ? `Na fila · começa em ${eta}` : 'Na fila'),
    moreInQueue: (n: number) => `+${String(n)} na fila`,
    cancel: 'Cancelar',
    cancelQueued: (title: string) => `Tirar ${title} da fila`,
    discard: 'Descartar',
    readyAgo: (ago: string) => `Pronta ${ago}`,
    openMixer: 'Abrir mixer',
    failedFallback: 'O processamento falhou.',
  },
  library: {
    title: 'Biblioteca',
    count: (n: number) => plural(n, 'sessão', 'sessões'),
    searchLabel: 'Buscar na biblioteca',
    searchPlaceholder: 'Buscar artista ou título',
    filtersLabel: 'Filtrar por estado',
    filters: {
      all: 'Todas',
      ready: 'Prontas',
      active: 'Em andamento',
      draft: 'Rascunhos',
      failed: 'Falhou',
    },
    filterCount: (label: string, n: number) => (n > 0 ? `${label} · ${String(n)}` : label),
    sortLabel: 'Ordenar',
    sorts: {
      newest: 'Mais recentes',
      oldest: 'Mais antigas',
      title: 'Título',
      artist: 'Artista',
      longest: 'Mais longas',
      shortest: 'Mais curtas',
    },
    columns: {
      code: 'Código',
      song: 'Música',
      state: 'Estado',
      duration: 'Duração',
      created: 'Criada',
      actions: 'Ações',
    },
    actions: {
      openMixer: 'Abrir mixer',
      follow: 'Acompanhar',
      continue: 'Continuar',
      retry: 'Tentar de novo',
      edit: 'Editar artista e título',
      reprocess: 'Reprocessar',
      delete: 'Excluir…',
    },
    emptyTitle: 'Nenhuma sessão ainda',
    emptyBody: 'Busque uma música para separar os primeiros stems.',
    emptyAction: 'Descobrir música',
    noMatchTitle: 'Nenhuma sessão aqui',
    noMatchBody: 'Mude o filtro ou a busca.',
    reprocessed: (code: string) => `${code} voltou para a fila`,
    edited: 'Artista e título atualizados',
    deleted: (code: string) => `${code} excluída`,
    editTitle: 'Editar artista e título',
    deleteTitle: (title: string) => `Excluir “${title}”?`,
    deleteBody: (code: string) =>
      `Os stems e os exports de ${code} serão apagados do disco. Não dá para desfazer.`,
    deleteConfirm: 'Excluir',
  },
  session: {
    back: 'Biblioteca',
    draftHint: 'Esta sessão ainda não foi processada. Confira artista e título e mande separar.',
    readyHint: 'Os stems estão prontos.',
    mixerSoon: 'O mixer chega em breve.',
    mixerSoonBody: 'Esta tela vai virar o mixer por stem (volume, pan, mute, solo e loop A–B).',
    openMixer: 'Abrir mixer',
    source: 'Ver no YouTube',
  },
  stems: {
    vocals: 'Voz',
    drums: 'Bateria',
    bass: 'Baixo',
    other: 'Outros',
  },
  mixer: {
    play: 'Tocar',
    pause: 'Pausar',
    back5: 'Voltar 5 segundos',
    forward5: 'Avançar 5 segundos',
    mute: (stem: string) => `Silenciar ${stem}`,
    solo: (stem: string) => `Solo de ${stem}`,
    volume: (stem: string) => `Volume de ${stem}`,
    pan: (stem: string) => `Pan de ${stem}`,
    markA: 'Marcar A',
    markB: 'Marcar B',
    clearLoop: 'Limpar loop',
    loading: 'Carregando os stems…',
  },
  devEngine: {
    title: 'Teste do AudioEngine',
    hint: 'Página técnica (só em desenvolvimento): toca os 4 stems e mede a sincronia.',
    pickSession: 'Sessão pronta',
    noSessions: 'Nenhuma sessão pronta. Processe uma música primeiro.',
    choose: 'Escolha…',
    state: 'Estado',
    context: 'AudioContext',
    latency: 'Latência base',
    drift: 'Desvio da mediana',
    spread: 'Espalhamento',
    clockOffset: 'Relógio − stems',
    corrections: 'Correções (velocidade / seek)',
    stalls: 'Travadas para carregar',
    heap: 'Heap JS',
    loop: 'Loop',
    noLoop: 'sem loop',
    measure: 'Medição',
    startMeasure: 'Iniciar medição',
    stopMeasure: 'Parar e gerar relatório',
    measuring: (seconds: number, samples: number) =>
      `Medindo há ${String(Math.floor(seconds))} s · ${String(samples)} leituras (meta: 180 s)`,
    copy: 'Copiar relatório',
    copied: 'Relatório copiado',
    copyFailed: 'Não deu para copiar; selecione o texto abaixo.',
    states: {
      idle: 'parado',
      loading: 'carregando',
      paused: 'pausado',
      playing: 'tocando',
      buffering: 'carregando dados',
    },
  },
  time: {
    today: 'hoje',
    yesterday: 'ontem',
    justNow: 'agora mesmo',
    minutesAgo: (n: number) => `há ${String(n)} min`,
    hoursAgo: (n: number) => `há ${String(n)} h`,
  },
} as const;
